# Generated by Django 4.2.1 on 2023-05-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Book name')),
                ('img', models.ImageField(upload_to='book_images', verbose_name='Book image')),
                ('price', models.PositiveIntegerField(verbose_name='Book price')),
                ('ganre', models.CharField(max_length=30, verbose_name='Book ganre')),
                ('about', models.TextField(verbose_name='Book about')),
            ],
        ),
    ]
